version: '3'
services: 
   php-fpm:
      image: php:7.2-fpm-alpine
      container_name: php-fpm
      volumes:
         - ./html:/var/www/html
         - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      ports:
         - 9000:9000

   nginx:
      image: nginx
      container_name: nginx
      depends_on:
         - php-fpm
      ports:
         - 80:80
      volumes:
         - ./html:/usr/share/nginx/html
         - ./default.conf:/etc/nginx/conf.d/default.conf
